create table Cars (
	id BIGSERIAL NOT NULL PRIMARY KEY,
	make  VARCHAR(100) NOT NULL,
	model VARCHAR(100) NOT NULL,
	price NUMARIC(19, 2) NOT NULL
);
insert into Cars (id, make , model, price) values (1, 'Lexus', 'GS', '$1.03');
insert into Cars (id, make , model, price) values (2, 'Land Rover', 'LR2', '$0.61');
insert into Cars (id, make , model, price) values (3, 'Acura', 'TL', '$1.12');
insert into Cars (id, make , model, price) values (4, 'Lotus', 'Esprit', '$1.67');
insert into Cars (id, make , model, price) values (5, 'Audi', 'A3', '$2.46');
insert into Cars (id, make , model, price) values (6, 'Chrysler', 'PT Cruiser', '$9.34');
insert into Cars (id, make , model, price) values (7, 'BMW', '7 Series', '$2.34');
insert into Cars (id, make , model, price) values (8, 'Chevrolet', 'Malibu', '$1.27');
insert into Cars (id, make , model, price) values (9, 'Mazda', 'MX-3', '$7.13');
insert into Cars (id, make , model, price) values (10, 'Oldsmobile', 'Achieva', '$7.01');
insert into Cars (id, make , model, price) values (11, 'Pontiac', 'Grand Prix', '$9.12');
insert into Cars (id, make , model, price) values (12, 'Chevrolet', 'Lumina', '$7.31');
insert into Cars (id, make , model, price) values (13, 'Buick', 'LaCrosse', '$5.81');
insert into Cars (id, make , model, price) values (14, 'Ford', 'F150', '$4.58');
insert into Cars (id, make , model, price) values (15, 'BMW', '3 Series', '$7.78');
insert into Cars (id, make , model, price) values (16, 'Volvo', 'V50', '$7.71');
insert into Cars (id, make , model, price) values (17, 'Geo', 'Tracker', '$3.46');
insert into Cars (id, make , model, price) values (18, 'Lexus', 'SC', '$4.68');
insert into Cars (id, make , model, price) values (19, 'Mitsubishi', 'Chariot', '$3.12');
insert into Cars (id, make , model, price) values (20, 'Chevrolet', 'Impala', '$1.20');
insert into Cars (id, make , model, price) values (21, 'Nissan', 'NV1500', '$9.06');
insert into Cars (id, make , model, price) values (22, 'Dodge', 'Ram 2500', '$6.66');
insert into Cars (id, make , model, price) values (23, 'Mazda', 'B-Series', '$4.33');
insert into Cars (id, make , model, price) values (24, 'Toyota', 'RAV4', '$0.36');
insert into Cars (id, make , model, price) values (25, 'Mitsubishi', 'Eclipse', '$7.74');
insert into Cars (id, make , model, price) values (26, 'Toyota', 'Camry Solara', '$1.19');
insert into Cars (id, make , model, price) values (27, 'Audi', 'S6', '$2.76');
insert into Cars (id, make , model, price) values (28, 'Isuzu', 'Space', '$0.38');
insert into Cars (id, make , model, price) values (29, 'Honda', 'Civic', '$9.31');
insert into Cars (id, make , model, price) values (30, 'Dodge', 'Ram Wagon B350', '$3.01');
insert into Cars (id, make , model, price) values (31, 'Volvo', 'V70', '$0.91');
insert into Cars (id, make , model, price) values (32, 'Audi', 'RS4', '$6.10');
insert into Cars (id, make , model, price) values (33, 'Mitsubishi', 'Eclipse', '$3.91');
insert into Cars (id, make , model, price) values (34, 'Saturn', 'Outlook', '$2.06');
insert into Cars (id, make , model, price) values (35, 'Subaru', 'XT', '$4.88');
insert into Cars (id, make , model, price) values (36, 'Toyota', 'Corolla', '$2.36');
insert into Cars (id, make , model, price) values (37, 'Audi', 'S4', '$9.62');
insert into Cars (id, make , model, price) values (38, 'Dodge', 'Challenger', '$3.85');
insert into Cars (id, make , model, price) values (39, 'Nissan', 'Xterra', '$8.89');
insert into Cars (id, make , model, price) values (40, 'Pontiac', 'Bonneville', '$4.79');
insert into Cars (id, make , model, price) values (41, 'Ford', 'Mustang', '$4.61');
insert into Cars (id, make , model, price) values (42, 'Chevrolet', 'Suburban 1500', '$8.94');
insert into Cars (id, make , model, price) values (43, 'Mercury', 'Marquis', '$9.41');
insert into Cars (id, make , model, price) values (44, 'Toyota', 'Yaris', '$4.17');
insert into Cars (id, make , model, price) values (45, 'Ford', 'Club Wagon', '$0.65');
insert into Cars (id, make , model, price) values (46, 'Infiniti', 'QX', '$4.84');
insert into Cars (id, make , model, price) values (47, 'Mazda', 'MX-6', '$5.00');
insert into Cars (id, make , model, price) values (48, 'Mazda', 'B-Series', '$5.63');
insert into Cars (id, make , model, price) values (49, 'Ford', 'Econoline E350', '$2.06');
insert into Cars (id, make , model, price) values (50, 'Volkswagen', 'Jetta', '$1.39');
insert into Cars (id, make , model, price) values (51, 'Oldsmobile', '88', '$9.48');
insert into Cars (id, make , model, price) values (52, 'Chevrolet', 'Suburban 2500', '$1.02');
insert into Cars (id, make , model, price) values (53, 'Volvo', 'XC90', '$6.61');
insert into Cars (id, make , model, price) values (54, 'Volvo', 'S60', '$3.29');
insert into Cars (id, make , model, price) values (55, 'Mercedes-Benz', '500SEC', '$6.35');
insert into Cars (id, make , model, price) values (56, 'Chevrolet', 'Aveo', '$5.54');
insert into Cars (id, make , model, price) values (57, 'Cadillac', 'CTS', '$9.48');
insert into Cars (id, make , model, price) values (58, 'Saturn', 'S-Series', '$1.21');
insert into Cars (id, make , model, price) values (59, 'Cadillac', 'Escalade ESV', '$5.14');
insert into Cars (id, make , model, price) values (60, 'Mercedes-Benz', 'CLK-Class', '$8.53');
insert into Cars (id, make , model, price) values (61, 'Volvo', 'S40', '$6.61');
insert into Cars (id, make , model, price) values (62, 'Audi', 'Q7', '$1.59');
insert into Cars (id, make , model, price) values (63, 'Oldsmobile', 'Alero', '$6.32');
insert into Cars (id, make , model, price) values (64, 'Chevrolet', 'Tahoe', '$3.20');
insert into Cars (id, make , model, price) values (65, 'MINI', 'Cooper', '$6.83');
insert into Cars (id, make , model, price) values (66, 'Pontiac', 'Firebird', '$2.10');
insert into Cars (id, make , model, price) values (67, 'Hyundai', 'Azera', '$4.63');
insert into Cars (id, make , model, price) values (68, 'Ford', 'Econoline E350', '$9.85');
insert into Cars (id, make , model, price) values (69, 'Ford', 'F250', '$6.21');
insert into Cars (id, make , model, price) values (70, 'Pontiac', '6000', '$4.91');
insert into Cars (id, make , model, price) values (71, 'Volkswagen', 'Golf', '$8.16');
insert into Cars (id, make , model, price) values (72, 'Audi', 'A8', '$2.81');
insert into Cars (id, make , model, price) values (73, 'Oldsmobile', 'Silhouette', '$0.62');
insert into Cars (id, make , model, price) values (74, 'GMC', 'Yukon XL 2500', '$3.31');
insert into Cars (id, make , model, price) values (75, 'GMC', 'Savana 3500', '$6.88');
insert into Cars (id, make , model, price) values (76, 'Suzuki', 'SJ 410', '$10.00');
insert into Cars (id, make , model, price) values (77, 'Nissan', 'Sentra', '$8.95');
insert into Cars (id, make , model, price) values (78, 'Ford', 'Mustang', '$4.03');
insert into Cars (id, make , model, price) values (79, 'Toyota', 'Avalon', '$0.65');
insert into Cars (id, make , model, price) values (80, 'Land Rover', 'Defender', '$5.70');
insert into Cars (id, make , model, price) values (81, 'Plymouth', 'Grand Voyager', '$2.64');
insert into Cars (id, make , model, price) values (82, 'Mazda', 'Miata MX-5', '$8.72');
insert into Cars (id, make , model, price) values (83, 'Lincoln', 'Navigator L', '$4.15');
insert into Cars (id, make , model, price) values (84, 'GMC', 'Suburban 2500', '$4.19');
insert into Cars (id, make , model, price) values (85, 'MINI', 'Cooper', '$3.12');
insert into Cars (id, make , model, price) values (86, 'Ford', 'Fusion', '$6.81');
insert into Cars (id, make , model, price) values (87, 'Chevrolet', 'Corvette', '$8.62');
insert into Cars (id, make , model, price) values (88, 'Pontiac', 'Sunfire', '$8.18');
insert into Cars (id, make , model, price) values (89, 'Citroën', 'CX', '$6.34');
insert into Cars (id, make , model, price) values (90, 'Chrysler', 'Grand Voyager', '$4.24');
insert into Cars (id, make , model, price) values (91, 'Mazda', 'Mazda3', '$7.25');
insert into Cars (id, make , model, price) values (92, 'Jeep', 'Wrangler', '$2.54');
insert into Cars (id, make , model, price) values (93, 'Chevrolet', 'Tahoe', '$9.85');
insert into Cars (id, make , model, price) values (94, 'Pontiac', 'Torrent', '$9.34');
insert into Cars (id, make , model, price) values (95, 'Chrysler', 'Town & Country', '$9.07');
insert into Cars (id, make , model, price) values (96, 'GMC', '1500 Club Coupe', '$2.22');
insert into Cars (id, make , model, price) values (97, 'Saturn', 'Outlook', '$7.18');
insert into Cars (id, make , model, price) values (98, 'Mitsubishi', 'Mighty Max', '$9.75');
insert into Cars (id, make , model, price) values (99, 'Mercury', 'Marquis', '$3.87');
insert into Cars (id, make , model, price) values (100, 'Toyota', 'Highlander', '$2.67');
